### PR TITLE
Fix issues

### LINKED ISSUE #79: set priority for showing charts

### LINKED ISSUE #166: Removing and adding a chart back throwing an error
screen shot 2016-08-15 at 9 36 55 am

### PR DESCRIPTION
**Pull request by kalletlak**
1. Fix #166 
2. Partial fix #79

### CODE REVIEW

File: app/scripts/views/mainTemplate.js [hunk 1]
```diff
@@ -62,30 +62,38 @@
...
+          });
+          this.updateGrid(ChartsIds);
+          this.messages.length=0;
+        }
       }
     }, methods: {
-      updateGrid: function() {
+      updateGrid: function(ChartsIds) {
+        var self_ = this;
+        function SortByNumber(a, b){
```
Comment (zhx828) [inline app/scripts/views/mainTemplate.js]: Can we make this a singleton? Maybe put it into util or maybe just inside the template vue methods object?

Comment (kalletlak) [inline app/scripts/views/mainTemplate.js]: Sure!. I'll move it to template methods.

File: app/scripts/vueCore.js [hunk 2]
```diff
@@ -150,13 +150,13 @@
               var attrData = self_.charts[attrId];
               var _attrAdded = false;
               var _group = {};
-              _.each(self_.groups,function(group){
+              _.every(self_.groups,function(group){
```
Comment (zhx828) [inline app/scripts/vueCore.js:153]: Any reason to switch to every?

Comment (kalletlak) [inline app/scripts/vueCore.js:153]: We can't break _.each. To break the loop I am using _.every

File: app/scripts/views/chartGroupTemplate.js [hunk 3]
```diff
@@ -126,19 +127,27 @@
...
-        this.invisibleChartFilters = val;
-        var filtersMap = {};
-        if(val.length>0){
-          _.each(val,function(filter){
+        var _groupCases = iViz.getGroupFilteredCases();
+        var _selectedCases = val;
+        var _self = this;
+        _.each(_groupCases,function(_group, id){
+          if(_group !== undefined && _group.type === _self.type && (_self.id.toString() !== id)){
+            _selectedCases = iViz.util.intersection(_selectedCases,_group.cases);
```
Comment (zhx828) [inline app/scripts/views/chartGroupTemplate.js]: This may cause performance issue. Should we use iViz.util.intersection instead?

File: app/scripts/views/mainTemplate.js [hunk 4]
```diff
@@ -62,30 +62,38 @@
...
+            dc.renderAll(group.id);
+          });
+          this.updateGrid(ChartsIds);
+          this.messages.length=0;
+        }
       }
     }, methods: {
-      updateGrid: function() {
+      sortByNumber: function(a, b){
+        var aName = Number(a.element.attributes['data-number'].nodeValue);
```
Comment (zhx828) [inline app/scripts/views/mainTemplate.js]: Should we deal with charts without data-number attributes? aName/bName will become undefined?
