### PR TITLE
Fix issues

### LINKED ISSUE #246: Remove all CopyRights in js files

### PR DESCRIPTION
**Pull request by zhx828**
Fixed #246 #253 #254 #255 #256 #260

### CODE REVIEW

File: app/scripts/model/dataProxy.js [hunk 1]
```diff
@@ -298,8 +308,14 @@ window.DataManagerForIviz = (function($, _) {
                     sequencedCases: _caseLists.allSampleIds
                   };
                 }
-                if (['CANCER_TYPE', 'CANCER_TYPE_DETAILED'].indexOf(_metaObj.attr_id) !== -1) {
-                  _metaObj.priority = 0.9;
+                if (['CANCER_TYPE', 'CANCER_TYPE_DETAILED']
+                    .indexOf(_metaObj.attr_id) !== -1) {
+                  if (Object.keys(_studyToSampleToPatientMap)
+                      .indexOf('MSKIMPACT') === -1) {
+                    _metaObj.priority = 4.1;
```
Comment (kalletlak) [inline app/scripts/model/dataProxy.js:315]: These priorities are hard coded( Changing priority depending on the study). May be we need to come up with a better solution in future release.

File: app/scripts/views/components/dataTable/tableView.js [hunk 2]
```diff
@@ -227,11 +227,15 @@
       }
       return assignedColors[key];
     }
+
     function initPieTableData() {
       _.each(group.all(), function(attr, index) {
+        if (!attr.value || attr.value === 'na') {
```
Comment (kalletlak) [inline app/scripts/views/components/dataTable/tableView.js]: Instead of checking it here why don't we do it at the time of creating dimension.

File: app/scripts/model/dataProxy.js (hunk 1 above)
Comment (zhx828) [reply app/scripts/model/dataProxy.js:315]: Agree.
