### PR TITLE
Fix issue #198 & #199

### LINKED ISSUE #199: Scatter plot issue : cases with no cna data
Currently it is set to 0 when there is no cna data.

b221d906-7224-11e6-94ac-cf902a744162

### PR DESCRIPTION
**Pull request by kalletlak**

### CODE REVIEW

File: app/scripts/views/components/scatterPlot/scatterPlot.js [hunk 1]
```diff
@@ -9,6 +9,17 @@
     var chartId_;
     var data_;
     var opts_;
+    var getQtipString = function(_data) {
+      var toReturn = 'Cancer Study:' + _data.study_id + '<br>Sample Id: ' +
+        _data.sample_id + '<br>CNA fraction: ';
+      if (isNaN(_data.cna_fraction)) {
```
Comment (zhx828) [inline app/scripts/views/components/scatterPlot/scatterPlot.js:15]: The situation is if the data isNaN, the case will not even be shown in scatter plot. It's ok to have this condition, but I don't think it will be used.

Comment (kalletlak) [reply app/scripts/views/components/scatterPlot/scatterPlot.js:15]: This is what the current cbioportal has. Cases with 'NA' cna or mutation count data are not shown.
