### PR TITLE
Use '_uids' instead of patient/sample ids

### LINKED ISSUE #150: Incorrect result when different studies have same sample ids

### PR DESCRIPTION
**Pull request by kalletlak**
Fix #150

### CODE REVIEW

File: app/scripts/main.js [hunk 1]
```diff
@@ -45,26 +41,11 @@ var iViz = (function(_, $, cbio, QueryByGeneUtil, QueryByGeneTextArea) {
...
-      }
-    });
-    return str;
-  }
-
   return {
 
     init: function(_rawDataJSON, opts) {
       vm_ = iViz.vue.manage.getInstance();
+      console.log(data_);
```
Comment (yichaoS) [inline app/scripts/main.js]: ? Testing line to get rid of?

File: app/scripts/model/dataProxy.js [hunk 2]
```diff
@@ -678,32 +703,27 @@ window.DataManagerForIviz = (function($, _) {
...
-                  _patientDataIndicesObj;
-                _result.groups.sample.data_indices.sample_id =
-                  _sampleDataIndicesObj;
-                _result.groups.group_mapping.sample = {};
-                _result.groups.group_mapping.patient = {};
-                _result.groups.group_mapping.sample.patient =
-                  _samplesToPatientMap;
-                _result.groups.group_mapping.patient.sample =
-                  _patientToSampleMap;
+                _result.groups = {
```
Comment (yichaoS) [inline app/scripts/model/dataProxy.js:696]: Could you please log this data structure in the wiki page? https://github.com/cBioPortal/iViz/wiki/Input-Data-JSON-Structure

Comment (kalletlak) [reply app/scripts/model/dataProxy.js:696]: updated

**Review by yichaoS — APPROVED** [review]
