### PR TITLE
Issues fixed for first milestone

### LINKED ISSUE #149: Abstract dimension implementation for regular/log scaled bar chart

### PR DESCRIPTION
**Pull request by zhx828**
There are known issues in cBioPortal: https://github.com/cBioPortal/cbioportal/issues/1622, will include these fixes after the issue solved.

### CODE REVIEW

**Comment by zhx828** [comment]
Fix #149: abstract regular/log dimension; 
Add outlier features: #177;
Fix #152
Fix #139

**Comment by zhx828** [comment]
The above commit https://github.com/cBioPortal/iViz/pull/178/commits/fe301e449a71bec63153f08c6fe05f5e8be884a9 is related to #79

File: app/scripts/controller/util.js [hunk 1]
```diff
@@ -630,6 +632,158 @@
...
+     * Compare based on data availability.
+     * Notice that: attribute with only one category will be moved to end.
+     * Number of keys in this attribute is more than half numOfDatum
+     * will be moved to end as well.
+     *
+     * @param {object} a Attribute meta item A.
+     * @param {object} b Attribute meta item B.
+     * @return {number} Indicator which item is selected.
+     */
+    content.compareClinicalAvailability = function(a, b) {
```
Comment (kalletlak) [inline app/scripts/controller/util.js:686]: In the next milestone as we are thinking of lazy loading to clinical data right, then how would we use this function? I mean we won't be having 'numOfDatum' info initially while loading right.

File: app/scripts/model/dataProxy.js [hunk 2]
```diff
@@ -340,28 +357,39 @@
...
             _osSurvivalAttrMeta.show = true;
-            _patientAttributes.unshift(_osSurvivalAttrMeta);
+            _osSurvivalAttrMeta.priority = 1;
+            _patientAttributes[_osSurvivalAttrMeta.attr_id] = _osSurvivalAttrMeta;
           }
 
           // add Cancer Study
           if (self.getCancerStudyIds().length > 1) {
-            _patientAttributes.unshift({
+            _patientAttributes['study_id'] = {
```
Comment (kalletlak) [inline app/scripts/model/dataProxy.js:421]: Should we add keys, numOfDatum, priority attributes to this meta object and even missing keys, numOfDatum to the above charts(tables survival and scatter meta).

File: app/scripts/model/dataProxy.js [hunk 3]
```diff
@@ -340,28 +357,39 @@
...
+            }
+          });
+          
           _result.groups = {};
           _result.groups.patient = {};
           _result.groups.sample = {};
           _result.groups.group_mapping = {};
-          _result.groups.patient.attr_meta = _patientAttributes;
-          _result.groups.sample.attr_meta = _sampleAttributes;
+          _result.groups.patient.attr_meta = iViz.util.sortClinicalAttrs(_.values(_patientAttributes));
```
Comment (kalletlak) [inline app/scripts/model/dataProxy.js]: Instead of applying 'sortClinicalAttrs' again why don't we use 'priority' attribute in each meta attribute to sort them?

File: app/scripts/controller/util.js (hunk 1 above)
Comment (zhx828) [reply app/scripts/controller/util.js:686]: Probably we need to calculate the priority every time we load additional attribute.

File: app/scripts/model/dataProxy.js (hunk 2 above)
Comment (zhx828) [reply app/scripts/model/dataProxy.js:421]: I thought about it. Not really necessary. It's nice to have but it needs couple few loops. These attributes are mostly designed specifically, and normally they are in preSelectedAttribtues or in clinicalAttrsPriority list. And I have https://github.com/cBioPortal/iViz/pull/178/commits/fe301e449a71bec63153f08c6fe05f5e8be884a9#diff-5baab798025ed50b358d0b2e1421cbe3R687 to deal with attributes without keys or numOfDatum

File: app/scripts/model/dataProxy.js (hunk 3 above)
Comment (zhx828) [reply app/scripts/model/dataProxy.js]: Good idea, will modify that.
