### PR TITLE
Fix issues

### LINKED ISSUE #219: Pie table should be changed to state after first click.
pie table select->unselect 
after clear all operation

### PR DESCRIPTION
**Pull request by kalletlak**
Fix #219, #222

### CODE REVIEW

File: app/scripts/views/components/dataTable/tableView.js [hunk 1]
```diff
@@ -219,9 +227,39 @@
...
+          _labelDatum.cases = _labelValue;
+          _currentSampleSize += _labelValue;
+          _labels[_labelDatum.id] = _labelDatum;
+        }
+      });
 
-    function initCategories(_selectedMap) {
-      var hasSelectedCases = _.isObject(_selectedMap);
+      _.each(_labels, function(label) {
+        label.caseRate = (_currentSampleSize <= 0 ? 0 : (Number(label.cases) * 100 / _currentSampleSize).toFixed(1).toString()) + '%';
```
Comment (zhx828) [inline app/scripts/views/components/dataTable/tableView.js]: You can use iViz.util.calcFreq(label.cases, _currentSampleSize)

Comment (kalletlak) [reply app/scripts/views/components/dataTable/tableView.js]: Sure
